print('What is your age', end=' ')
age = input()
print('What is your height', end=' ')
height = input()
print('What is your weight', end=' ')
weight = input()
print(f'Your age is {age}\nyour height is {height} and your weight is {weight}')
